version: '3.0'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html

  php-fpm:
    build: .
    container_name: php
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./php/php.ini-production:/usr/local/etc/php/php.ini:ro
      - ./php/log:/var/log/php-fpm
      - ./nginx/html:/var/www/html

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "mysql&7"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d：将主机当前目录下的 conf/my.cnf 挂载到容器的 /etc/mysql/my.cnf。
      - ./mysql/logs:/logs：将主机当前目录下的 logs 目录挂载到容器的 /logs。
      - ./mysql/data:/var/lib/mysql ：将主机当前目录下的data目录挂载到容器的 /var/lib/mysql 。
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  netease_cloud_music_api:
    build: ./NeteaseCloudMusicApi-3.47.2
    container_name: netease_cloud_music_api
    restart: always
    ports:
      - 3000:3000
